picture:
    pattern:  /
    defaults: { _controller: "AzgilGalleryBundle:Picture:index" }

picture_show:
    pattern:  /{id}/show
    defaults: { _controller: "AzgilGalleryBundle:Picture:show" }

picture_new:
    pattern:  /new
    defaults: { _controller: "AzgilGalleryBundle:Picture:new" }

picture_create:
    pattern:  /create
    defaults: { _controller: "AzgilGalleryBundle:Picture:create" }
    requirements: { _method: post }

picture_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AzgilGalleryBundle:Picture:edit" }

picture_update:
    pattern:  /{id}/update
    defaults: { _controller: "AzgilGalleryBundle:Picture:update" }
    requirements: { _method: post|put }

picture_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AzgilGalleryBundle:Picture:delete" }
    requirements: { _method: post|delete }
